--/*
--  HIVE SCRIPT  : create_dim_member_multi_phone.hql
--  AUTHOR       : Neha Mahajan
--  DATE         : May 12, 2017
--  DESCRIPTION  : Creation of hive gold.dim_member_multi_phone
--*/
USE ${hiveconf:database};
DROP TABLE IF EXISTS  ${hiveconf:namespace}${hiveconf:table_name};
CREATE EXTERNAL TABLE ${hiveconf:database}.${hiveconf:namespace}${hiveconf:table_name}(
MEMBER_MULTI_PHONE_KEY BIGINT,
MEMBER_KEY BIGINT,
PHONE_NUMBER STRING,
PHONE_TYPE STRING,
PHONE_CONSENT STRING,
PHONE_CONSENT_DATE TIMESTAMP,
VALID_PHONE STRING,
BEST_MOBILE_FLAG STRING,
BEST_MEMBER STRING,
IS_LOYALTY_FLAG STRING,
SOURCE_KEY BIGINT,
ORIGINAL_SOURCE_KEY BIGINT,
MATCH_TYPE_KEY BIGINT,
LAST_UPDATED_DATE TIMESTAMP,
BATCH_ID STRING)
PARTITIONED BY
(STATUS STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\u0001'
STORED AS ORC
LOCATION '${hiveconf:location}';
